### ISSUE TITLE
Add db default for tests

### ISSUE THREAD

**Issue by smacker** [src-d/metadata-retrieval#46]
running `go test ./...` on master connects to `postgres://:@localhost:5432/?sslmode=disable` which doesn't raise error but connect to "default" database which is unexpected.

//cc @kyrcha

**Comment by se7entyse7en** [comment]
Related to this, IMO it makes sense to set also `PSQL_{USER,PWD}` to the default used by the `docker-compose.yml`, and to also document that they have to set in the `README.md`.

**Comment by kyrcha** [comment]
I am a fan of the approach: `make your software more robust by making it more fragile`, thus if the env vars are not set perhaps the method should return an error (and exit), but since in this repo we propose the use of docker-compose with default USR/PWD it makes also sense to initialize with default values.

**Comment by smacker** [comment]
I'm ok with an error too. The current problem the tests were failing (migration has changed) and I couldn't figure out how come for a while. Where did it save the previous migration.

**Comment by kyrcha** [comment]
I was waiting for the migrations too, but had to do:
```
docker-compose exec postgres psql -U user -d postgres -c "drop database ghsync;"
docker-compose exec postgres psql -U user -d postgres -c "create database ghsync;"
```
since there only seems to be 1 migration file

**Comment by se7entyse7en** [comment]
> I'm ok with an error too. The current problem the tests were failing (migration has changed) and I couldn't figure out how come for a while. Where did it save the previous migration.

So to be clear the tests were failing when trying to migrate?

**Comment by kyrcha** [comment]
Most probably at least in my case the problem was that:

1. The migration file `000001_init.up.sql` run the first time 
2. The tables changed and so was the `000001_init.up.sql` at some later point
3. The migration script in my dev env did not run the `000001_init.up.sql` file since it had already run
4. No new columns were added
5. Got errors and thus had to drop and re-create the DB

In the Travis env it always runs OK because it creates a new docker container every time

In any case in the tests I will ask for the env vars to be set, else the tests will fail.

**Comment by smacker** [comment]
Yeah. As we don't have a release yet we modify initial migration and it requires drop of the db.
After the release db changes will be done properly in new migration files but switching between branches would still require drop from time to time as if we add a new migration in one branch and then switch to another one, migration file won't be found and migration fail. It's normal.

My issue, it was hard to find where I actually need to run `drop` as it is connecting to `postgres://:@localhost:5432/?sslmode=disable`.
