### ISSUE TITLE
Tune number of resourses for fat requests

### ISSUE THREAD

**Issue by smacker** [src-d/metadata-retrieval#69]
Downloading `src-d` organization (189 repos) caused ~100 errors 502 due to timeout on github side, most of which were for the first fast requests.

It makes sense to experiment a little with the numbers and see if we can reduce the number of errors without making it slower.

**Comment by dpordomingo** [comment]
GH docs say that the max number of nodes is 500k, but [I could reproduce this error with much fewer nodes ~1.5k nodes](https://github.community/t5/GitHub-API-Development-and/Persistent-502-when-querying/m-p/34380#M3212). I wonder if that limit can occur randomly, or depending on how much demanded their servers are. If that's the case, it may happen that we choose a too low or big number

crazy idea: being able to reduce the page size if getting a `502`, finding dynamically the one that works.

**Comment by dpordomingo** [comment]
From the conversation I had with `lee-dohm` from gh support, I assume that the `502` can happen from time to time, no matter the page sizes you stablish in your queries.
As you can see there, the same query didn't work when I opened the issue, but it did some days later, and there is no guarantee that it will in the future, so we can assume that we may find a limit now, which may be too low at any moment, and to high in others.

**Comment by smacker** [comment]
502 would happen most of the time for big queries when they don't have cache for this.
The idea of this issue is to decrease a little bit the numbers to reduce number of such errors for the majority of the repositories for now.
If github improves their backend in the future we can re-tune the numbers.

**Comment by dpordomingo** [comment]
>_If github improves their backend in the future we can re-tune the numbers._
Yes, it would be great.
I just wonder how're we noticing it.

**Comment by se7entyse7en** [comment]
As @smacker 502 will still happen, always. That could be caused by anything, the node limit explained in the doc it's just a condition that for sure will make your request fail, but it doesn't mean that not hitting it won't get you to receive a 502. So in other words, a response error is sufficient condition for hitting the limit, but not a necessary one.

> If github improves their backend in the future we can re-tune the numbers.

+1

> I just wonder how're we noticing it.

You won't 😄. I mean you won't even think about it until the performances become a problem. Once they become a problem you'll most probably consider looking at these numbers again.

**Comment by dpordomingo** [comment]
So we're only changing the number to make it smaller and smaller, as the performance can be eventually worst, so, in fact, we're always using the smallest known limit.

**Comment by se7entyse7en** [comment]
I didn't do many tests, but here are the ones that I did:

| id |   issues & PRs  | warmed | duration | 502s | total requests | 502s % |
|:--:|:---------------:|:------:|:--------:|:----:|:--------------:|:------:|
|  1 | 50-50 (no tune) |        |   26m8s  |  49  |      2437      |  2.01% |
|  2 | 50-50 (no tune) |    X   |  16m14s  |   1  |      2388      |  0.04% |
|  3 |      25-25      |        |  18m31s  |   0  |      2570      |   0%   |
|  4 |      25-25      |    X   |   18m4s  |   0  |      2570      |   0%   |
|  5 |      35-35      |        |  18m16s  |   1  |      2468      |  0.04% |
|  6 |      40-40      |        |   24m5s  |   5  |      2435      |  0.20% |

I played only with the initial number of issues and PRs and always change them with the same number.

The baseline is the row with `id: 1`. The `warmed` column means that it has been launched after a previous run, so some data could have been potentially cached. The rows with `id: [1, 2, 4]` were run on Friday, the row with `id: 3` on Saturday, the row with `id: 5` on Sunday and the row with `id: 6` today.

This is not for sure (and doesn't meant to be) a proper formal analysis, but just to have an idea.

It's clear that warming had an effect by looking at rows with `id: [1, 2]`. In case of row with `id: 4`, it cannot be appreciated as even with non-warmed run it doesn't produce any 502.

The row with `id: 5` seems the best choice producing only 0.04% of 502s. WRT to duration, I'm not confident in comparing them, because most probably running some of the tests during weekends affected the results. But again this is not a formal analysis.

An important thing to note is also that this has been tested for our organization, so results may vary a lot.

Conclusion: I'd go for `35-35`.

**Comment by se7entyse7en** [comment]
Once we agreed, I'll open the corresponding PR.

**Comment by smacker** [comment]
Sounds good to me. But I would re-run it today as the load on github during weekends is different from weekdays. It might affected the numbers.

**Comment by se7entyse7en** [comment]
> the load on github during weekends is different from weekdays. It might affected the numbers.

yup, I was thinking the same. I'm re-running `35-35`, I don't know how their caching works, but I ran `40-40` this morning, so I would consider this run as a _fresh_ one.

**Comment by se7entyse7en** [comment]
Re-ran `35-35`:

| duration | 502s | total requests | 502s % |
|:--------:|:----:|:--------------:|:------:|
|   20m45s  |  0  |      2467      |  0% |

**Comment by dpordomingo** [comment]
I don't understand how and what did you tested in these scenarios?

| id |   issues & PRs  | warmed | duration | 502s | total requests | 502s % |
|:--:|:---------------:|:------:|:--------:|:----:|:--------------:|:------:|
|  1 | 50-50 |        |   26m8s  |  49  |      2437      |  2.01% |
|  5 | 35-35 |        |  18m16s |   1   |      2468      |  0.04% |

When using `50-50` and `35-35`, did you do ~2.4k total requests in both cases?
so... did you received 50% fewer documents when using `35-35`?

I'm assuming that 1 request using `50-50` will fetch 2500 nodes, and `35-35` 1225 nodes instead.
Then, in order to get the rest of the nodes (that were fetched with `50-50`) it would be needed 3 extra calls `35-last:15,`, `last:15-35` and `last:15-last:15`, what would most probably consume more time that consumed by only one `50-50`.

An alternative would be that the times you provided already considered the extra calls that I mentioned, which would be unexpected for me, because it would mean that those 4 smaller requests would be double faster than only one 50% bigger.

**Comment by se7entyse7en** [comment]
> I'm assuming that 1 request using 50-50 will fetch 2500 nodes, and 35-35 1225 nodes instead.
Then, in order to get the rest of the nodes (that were fetched with 50-50) it would be needed 3 extra calls 35-last:15,, last:15-35 and last:15-last:15, what would most probably consume more time that consumed by only one 50-50.

Sorry but I don't understand this part. But one thing that I think I understood is that you imply that more requests would take more time than a single one, but why it should be? It depends on the request.

> When using 50-50 and 35-35, did you do ~2.4k total requests in both cases?

yup, the numbers to tune in questions changes only the first fat request for each repo. Not the number of each request. For non-first request the limit is hard-coded to `100`. PRs are an exception for which the same page is always applied.

> An alternative would be that the times you provided already considered the extra calls that I mentioned, which would be unexpected for me, because it would mean that those 4 smaller requests would be double faster than only one 50% bigger.

The times are those printed by the logger.

I don't understand a couple of things. For example in scenario number `1` I had 49 502s. Let's say that those errors were all produced while fetching the first page of repo, and that for that repo a single request with `50-50` would have been enough. Most probably failing `49` times the same request would take much more then 2 request with a lower setup as `35-35`.

**Comment by se7entyse7en** [comment]
And also as I said I ran the experiments in different days, so the timing is not really that much reliable. Having a reliable idea of timing would require a much formal process.

**Comment by dpordomingo** [comment]
Sorry, I misunderstood the problem with the first request, used to fetch only some initial data for each repo.

So now, let me confirm if I can do these assumptions from your table:
- once the **502s%** is low enough (maybe `<0.1%`), the time needed to finish is almost the same (`~18min`), no matter what config you apply: `50-50` after warmup, `35-35` or `25-25`.
- as higher the **502s%** is, the slower the process takes (I assume because the `502` takes the same amount of time to be processed than the same query when it returned `200`),
- the **502s%** rate increases as the fat requests increases its weight.

If those assumptions are right, it would mean that:
- the fat request seems to have no impact on the elapsed time if the **502s%** is low enough,
- high **502s%** rates have a lot of impact in the elapsed time.

Then, since the fat request has no special impact in the elapsed time, and it's crucial to minimize **502s%** rate, which depends on the fat request, why not using the lowest config as possible? (the edge case would be `1-1`)

**Comment by se7entyse7en** [comment]
> once the 502s% is low enough (maybe <0.1%), the time needed to finish is almost the same (~18min), no matter what config you apply: 50-50 after warmup, 35-35 or 25-25.

It depends on the meaning of _almost the same_. As you can see I re-ran the `35-35` on Monday and it took ~21mins.

> - as higher the 502s% is, the slower the process takes (I assume because the 502 takes the same amount of time to be processed than the same query when it returned 200),
> - the 502s% rate increases as the fat requests increases its weight.

These are also my guesses. 👍 

> - the fat request seems to have no impact on the elapsed time if the 502s% is low enough,

That's the point. I cannot tell this for sure. For each scenario, except for `35-35`, I only have a single datapoint. In order to conclude that the initial fat request have no impact I'd at least run 10 times for each scenario, then I may come to this conclusion, but not with the current data.

Also `fat request [...] have no impact [...] if the 502s% is low`, but that's because most of the `502s` are caused by the initial fat requests. They don't seem to be independent.

> - high 502s% rates have a lot of impact in the elapsed time.

It seems to be apparently.

**Comment by se7entyse7en** [comment]
BTW I'm running 1-1 and see what happens 👍.

**Comment by se7entyse7en** [comment]
Here's the result for `1-1`:

| duration | 502s | total requests | 502s % |
|:--------:|:----:|:--------------:|:------:|
|  1h3m33s  |  0  |      11188      |  0% |

**Comment by se7entyse7en** [comment]
> Sorry, I misunderstood the problem with the first request, used to fetch only some initial data for each repo.

The only exception is for PRs:

> PRs are an exception for which the same page is always applied.

That's why using 1-1 the number of total requests is much bigger.
